# Generated by Django 2.2 on 2020-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(max_length=100),
        ),
    ]
